### ISSUE TITLE
Add Compatibility for Keechallenge Plugin

### ISSUE THREAD

**Issue by tristan-k** [kylemanna/keepassx#10]
[Quote:](https://github.com/keepassx/keepassx/pull/52)
> Breaks the ability to open the KeePass2 database by anything other then KeePassX with YubiKey support. Perhaps KeePass2 could open it with a plugin, but I didn't look at it.
> - kylemanna

There is Plugin called [keechallenge](https://github.com/brush701/keechallenge) which is also compatible to [Keepass2Android](https://keepass2android.codeplex.com/wikipage?title=How%20to%20use%20Keepass2Android%20with%20YubiKey%20NEO&referringTitle=Documentation). Please add compatibility for KeePass 2 Keechallenge Plugin.

**Comment by kylemanna** [comment]
You're misunderstanding my quote.  KeePassX + Yubikey patches can open any *regular* KeePass2 database just fine.  The point of my quote was to say *if* you add the Yubikey support to a database file you can only open it with my tool or develop your own (the implementation is opensource).

I know for a fact that this version of keepassx + yk support can open standard keepass2 databases on Linux and Mac OS X.

Keechallenge is fundamentally different as it stores the metadata in a separate XML file.  This approach is undesirable and clumsy to me.

**Comment by tristan-k** [comment]
Thanks for pointing that out.
