### ISSUE TITLE
Restore Lost YubiKeyq

### ISSUE THREAD

**Issue by AgeManning** [kylemanna/keepassx#19]
In other implementations I've seen features such as a large backup key that can be used to recover a database if a yubikey is lost/damaged. 

It seems in this implementation, if the yubikey is lost, the entire database is as well?

**Comment by kylemanna** [comment]
There are several ways to solve this.

First, I'd just order two Yubikey's and copy the private key to both.  Key can be generated by an offline computer for the paranoid.  I'd recommend doing this for all  Yubikey functions.  Securely store one, and carry the other around.  In the event of loss, you have the back-up.

Second, @pgalves has written a [CLI recovery tool](https://github.com/kylemanna/keepassx/pull/6). You'd need to backup the challenge response key upon generation in the Yubikey personalization tool.

**Comment by AgeManning** [comment]
Ok thanks, 
I'll check out the recovery tool.
