### ISSUE TITLE
Scan for Yubikey [Improvement]

### ISSUE THREAD

**Issue by AgeManning** [kylemanna/keepassx#20]
I currently have keepassx run on startup. It does not give me the option to use challenge response when I plug in the yuibkey. 

It seems the yuibkey must be inserted before the application starts. 

Potential improvement would be to get Keepassx to recognise a yubikey as been inserted, or allow a user to manually select the challenge response without having to restart.

**Comment by kylemanna** [comment]
This is a known issue.  Should this fork have the chance to continue upstream then hot plug detection could be added.  Until that happens, complicating the patch will be avoided.
