### ISSUE TITLE
Possible data loss when database is closed while YubiKey is unplugged

### ISSUE THREAD

**Issue by fabian-z** [kylemanna/keepassx#4]
When the YubiKey is not plugged in while closing the database and one decides to save the changes, the error message ("Unable to issue challenge-response") will appear but closing the database will proceed afterwards, losing the previous changes since the last save.

Steps to reproduce:
1) Open challenge-response secured KDBX.
2) Change any entry (remove, add, etc.)
3) Unplug YubiKey
4) Try to close the database, selecting Yes when asked if you want to save changes.
5) Closing the database will proceed after an error message. Changed entry from 2. will be lost/unchanged.

Expected Behaviour:
Stop database close if an error during saving occurs. The user can re-plug his YubiKey afterwards, save and retry to close the database afterwards.

**Comment by kylemanna** [comment]
Just rebased the fork on top of the upstream master.  There are some fixes in there to prevent this from happening.  Please test and re-open if you encounter the issues still!
