### ISSUE TITLE
Unable to use Yubikey

### ISSUE THREAD

**Issue by computerfr33k** [kylemanna/keepassx#8]
It seems that the challenge response mode is disabled for me.
I'm unsure why this is disabled for me, I am using Arch Linux and it found the yubikey libs correctly.
![screenshot from 2015-06-11 17-15-37](https://cloud.githubusercontent.com/assets/2096910/8119759/aa5e8d06-105d-11e5-9976-beaa6bba0308.png)

**Comment by computerfr33k** [comment]
Just found out that it needs to be in HMAC-SHA1 mode instead of Yubico OTP. It is now working for me.

**Comment by kylemanna** [comment]
Welcome to the Yubikey club!  Glad you got it working and thanks for pointing out my b0rked AUR.

My overview in the upstream PR: https://github.com/keepassx/keepassx/pull/52
