### ISSUE TITLE
Patch need to be ported in KeePassX-2.0-beta1

### ISSUE THREAD

**Issue by ufovsalien** [kylemanna/keepassx#9]
Patch need to be ported in KeePassX-2.0-beta1

**Comment by kylemanna** [comment]
Definitely agree.  Need to port it forward at some point.  Might wait for the next release.  Thoughts?

**Comment by ufovsalien** [comment]
I tried porting myself, but without success.

**Comment by kylemanna** [comment]
Just rebased the fork on top of the upstream master.  Please give it a test!

**Comment by ufovsalien** [comment]
Just yesterday night thought about try porting myself again, and received this cool news about update today.  :+1: 
 Already updated package with new keepassx in mine ppa: https://launchpad.net/~hda-me/+archive/ubuntu/keepassx2-yubico

**Comment by kylemanna** [comment]
Awesome!  Thanks for putting together the PPA!
